#!/bin/bash
wget https://standards.iso.org/iso/15118/-20/ed-1/en/V2G_CI_AppProtocol.xsd -O ${1}V2G_CI_AppProtocol.xsd
wget https://standards.iso.org/iso/15118/-20/ed-1/en/V2G_CI_CommonTypes.xsd -O ${1}V2G_CI_CommonTypes.xsd
wget https://standards.iso.org/iso/15118/-20/ed-1/en/V2G_CI_CommonMessages.xsd -O ${1}V2G_CI_CommonMessages.xsd
wget https://standards.iso.org/iso/15118/-20/ed-1/en/V2G_CI_AC.xsd -O ${1}V2G_CI_AC.xsd
wget https://standards.iso.org/iso/15118/-20/ed-1/en/V2G_CI_DC.xsd -O ${1}V2G_CI_DC.xsd
wget https://standards.iso.org/iso/15118/-20/ed-1/en/V2G_CI_ACDP.xsd -O ${1}V2G_CI_ACDP.xsd 
wget https://standards.iso.org/iso/15118/-20/ed-1/en/V2G_CI_WPT.xsd -O ${1}V2G_CI_WPT.xsd
wget https://standards.iso.org/iso/15118/-20/ed-1/en/xmldsig-core-schema.xsd -O ${1}xmldsig-core-schema.xsd 
